variables:
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - deploy

.virtenv: &virtualenv
  - python -m venv buildenv
  - . buildenv/bin/activate

build:
  # This stage only tests if the installation is possible.
  # The evironment created herein will be discared and re-created in the test stage.
  stage: build
  tags:
    - panelaero
  script:
    - *virtualenv
    - pip install .

test:
  stage: test
  timeout: 3 hours
  coverage: '/^TOTAL.+?(\d+\%)$/'
  tags:
    - panelaero
  dependencies:
    - build
  script:
    - *virtualenv
    # Install with -e (in editable mode) to allow the tracking of the test coverage
    - pip install -e .
    - which python
    - which pytest
    # Run the actual testing
    - pytest -v --basetemp=./test_tmp --cov-report xml:coverage.xml --cov=panelaero --junitxml=testresult.xml
    - coverage xml -o coverage.xml
    - coverage report
    - coverage html --directory ./coverage
  artifacts:
    when: always
    paths:
      - coverage.xml
      - testresult.xml
      - coverage
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: testresult.xml

pages:
  stage: deploy
  tags:
    - panelaero
  dependencies:
    - test
  script:
    - mkdir public
    - mv coverage public/coverage
  artifacts:
    paths:
      - public
